name: zim_phone_utils_dart
description: Utilities for validating, formatting, and detecting Zimbabwean mobile and landline phone numbers in Dart.
version: 1.0.0
homepage: https://github.com/eisax/zim_phone_utils_dart
# repository: https://github.com/eisax/zim_phone_utils_dart

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
